/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author IDAT
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        btnRegistroAlquiler = new javax.swing.JButton();
        btnRegistrarCliente = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnAsignacion = new javax.swing.JButton();
        btnCalculoTarifa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Principal");
        getContentPane().setLayout(null);

        jPanel5.setBackground(new java.awt.Color(51, 51, 255));
        jPanel5.setLayout(null);

        btnRegistroAlquiler.setBackground(new java.awt.Color(102, 153, 255));
        btnRegistroAlquiler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RegistrodeAlquileres (2).png"))); // NOI18N
        btnRegistroAlquiler.setText("Registro de Alquileres");
        btnRegistroAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroAlquilerActionPerformed(evt);
            }
        });
        jPanel5.add(btnRegistroAlquiler);
        btnRegistroAlquiler.setBounds(0, 242, 310, 37);

        btnRegistrarCliente.setBackground(new java.awt.Color(102, 153, 255));
        btnRegistrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Clientes.png"))); // NOI18N
        btnRegistrarCliente.setText("Registrar Cliente");
        btnRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClienteActionPerformed(evt);
            }
        });
        jPanel5.add(btnRegistrarCliente);
        btnRegistrarCliente.setBounds(0, 420, 310, 37);

        btnReporte.setBackground(new java.awt.Color(102, 153, 255));
        btnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Reporte.png"))); // NOI18N
        btnReporte.setText("Reporte ");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        jPanel5.add(btnReporte);
        btnReporte.setBounds(0, 480, 310, 37);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/images.jpg"))); // NOI18N
        jPanel5.add(jLabel2);
        jLabel2.setBounds(46, 14, 258, 189);

        btnSalir.setBackground(new java.awt.Color(102, 153, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel5.add(btnSalir);
        btnSalir.setBounds(0, 540, 310, 37);

        btnAsignacion.setBackground(new java.awt.Color(102, 153, 255));
        btnAsignacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Asignación.png"))); // NOI18N
        btnAsignacion.setText("Asignación");
        btnAsignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignacionActionPerformed(evt);
            }
        });
        jPanel5.add(btnAsignacion);
        btnAsignacion.setBounds(0, 310, 310, 37);

        btnCalculoTarifa.setBackground(new java.awt.Color(102, 153, 255));
        btnCalculoTarifa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CalculoDeTarifas.png"))); // NOI18N
        btnCalculoTarifa.setText("Cálculo de Tarifas");
        btnCalculoTarifa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculoTarifaActionPerformed(evt);
            }
        });
        jPanel5.add(btnCalculoTarifa);
        btnCalculoTarifa.setBounds(0, 365, 310, 37);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(6, -4, 310, 690);

        setSize(new java.awt.Dimension(331, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        
        // Mostrar el JOptionPane con las opciones Sí/No
        int respuesta = JOptionPane.showConfirmDialog(null, 
            "¿Deseas abrir otra ventana?", "Confirmación", 
            JOptionPane.YES_NO_OPTION);
        
        // Si el usuario selecciona "Sí" (YES_OPTION)
        if (respuesta == JOptionPane.YES_OPTION) {
            // Crear y mostrar otra ventana (puede ser un JOptionPane u otra ventana)
            JOptionPane.showMessageDialog(null, "¡Se abrió otra ventana!", 
                                          "Nueva Ventana", JOptionPane.INFORMATION_MESSAGE);
            frmLogin Regresar = new frmLogin();

            // Mostrar la nueva ventana
            Regresar.setVisible(true);

            // Cerrar la ventana actual
            this.dispose();
        } else {
            // Si el usuario selecciona "No" (NO_OPTION)
            /*JOptionPane.showMessageDialog(null, "No se abrirá otra ventana.", 
                                          "Cancelado", JOptionPane.INFORMATION_MESSAGE);*/
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAsignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignacionActionPerformed
        
    }//GEN-LAST:event_btnAsignacionActionPerformed

    private void btnRegistroAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroAlquilerActionPerformed
       
        
    }//GEN-LAST:event_btnRegistroAlquilerActionPerformed

    private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienteActionPerformed
        
        
    }//GEN-LAST:event_btnRegistrarClienteActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnCalculoTarifaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculoTarifaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalculoTarifaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignacion;
    private javax.swing.JButton btnCalculoTarifa;
    private javax.swing.JButton btnRegistrarCliente;
    private javax.swing.JButton btnRegistroAlquiler;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
