/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author IDAT
 */
public class frmPrincipal extends javax.swing.JFrame {
    private JFrame ventanaActual = null; // 🔹 Guarda la ventana que está abierta
    
    public frmPrincipal() {
        initComponents();
        btnRegistrarCliente.addActionListener(e -> abrirVentana(new frmRegistrarClientes()));
        btnRegistrarVehiculo.addActionListener(e -> abrirVentana(new frmRegistroVehiculos()));
        btnAsignarVehiculo.addActionListener(e -> abrirVentana(new frmAsignacionVehiculos()));
        btnCalcularTarifas.addActionListener(e -> abrirVentana(new frmCalculoTarifas()));
        btnReporteIngresos.addActionListener(e -> abrirVentana(new frmReporteIngresos()));
        btnListaClientes.addActionListener(e -> abrirVentana(new frmListaClientes()));
        btnListaVehiculos.addActionListener(e -> abrirVentana(new frmListaVehiculos()));
        btnListaAlquileres.addActionListener(e -> abrirVentana(new frmListaAlquileres()));
        btnConfiguracion.addActionListener(e -> abrirVentana(new frmConfiguracion()));

        setVisible(true);
    }
    // 🔹 Método para manejar la apertura de ventanas
    private void abrirVentana(JFrame nuevaVentana) {
        if (ventanaActual != null) {
            ventanaActual.dispose(); // 🔹 Cierra la ventana anterior si existe
        }
        ventanaActual = nuevaVentana; // 🔹 Guarda la nueva ventana abierta
        ventanaActual.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnRegistrarVehiculo = new javax.swing.JButton();
        btnRegistrarCliente = new javax.swing.JButton();
        btnReporteIngresos = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnAsignarVehiculo = new javax.swing.JButton();
        btnCalcularTarifas = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnListaClientes = new javax.swing.JButton();
        btnListaVehiculos = new javax.swing.JButton();
        btnListaAlquileres = new javax.swing.JButton();
        btnConfiguracion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Principal");
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/images.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 10, 225, 225);

        jPanel5.setBackground(new java.awt.Color(51, 51, 255));
        jPanel5.setLayout(null);

        btnRegistrarVehiculo.setBackground(new java.awt.Color(102, 153, 255));
        btnRegistrarVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RegistrodeAlquileres (2).png"))); // NOI18N
        btnRegistrarVehiculo.setText("Registrar Vehículo");
        btnRegistrarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVehiculoActionPerformed(evt);
            }
        });
        jPanel5.add(btnRegistrarVehiculo);
        btnRegistrarVehiculo.setBounds(0, 250, 240, 37);

        btnRegistrarCliente.setBackground(new java.awt.Color(102, 153, 255));
        btnRegistrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Clientes.png"))); // NOI18N
        btnRegistrarCliente.setText("Registrar Cliente");
        btnRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClienteActionPerformed(evt);
            }
        });
        jPanel5.add(btnRegistrarCliente);
        btnRegistrarCliente.setBounds(0, 420, 240, 37);

        btnReporteIngresos.setBackground(new java.awt.Color(102, 153, 255));
        btnReporteIngresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Reporte.png"))); // NOI18N
        btnReporteIngresos.setText("Reporte de Ingresos");
        btnReporteIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteIngresosActionPerformed(evt);
            }
        });
        jPanel5.add(btnReporteIngresos);
        btnReporteIngresos.setBounds(0, 480, 240, 37);

        btnSalir.setBackground(new java.awt.Color(102, 153, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel5.add(btnSalir);
        btnSalir.setBounds(0, 540, 90, 37);

        btnAsignarVehiculo.setBackground(new java.awt.Color(102, 153, 255));
        btnAsignarVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Asignación.png"))); // NOI18N
        btnAsignarVehiculo.setText("Asignar Vehículo");
        btnAsignarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarVehiculoActionPerformed(evt);
            }
        });
        jPanel5.add(btnAsignarVehiculo);
        btnAsignarVehiculo.setBounds(0, 310, 240, 37);

        btnCalcularTarifas.setBackground(new java.awt.Color(102, 153, 255));
        btnCalcularTarifas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CalculoDeTarifas.png"))); // NOI18N
        btnCalcularTarifas.setText("Cálculo de Tarifas");
        btnCalcularTarifas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularTarifasActionPerformed(evt);
            }
        });
        jPanel5.add(btnCalcularTarifas);
        btnCalcularTarifas.setBounds(0, 365, 240, 37);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(6, -4, 250, 690);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(null);

        btnListaClientes.setBackground(new java.awt.Color(51, 51, 255));
        btnListaClientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnListaClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnListaClientes.setText("Listado de Clientes");
        jPanel2.add(btnListaClientes);
        btnListaClientes.setBounds(30, 250, 190, 30);

        btnListaVehiculos.setBackground(new java.awt.Color(51, 51, 255));
        btnListaVehiculos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnListaVehiculos.setForeground(new java.awt.Color(255, 255, 255));
        btnListaVehiculos.setText("Listado de Vehículos");
        jPanel2.add(btnListaVehiculos);
        btnListaVehiculos.setBounds(30, 310, 190, 30);

        btnListaAlquileres.setBackground(new java.awt.Color(51, 51, 255));
        btnListaAlquileres.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnListaAlquileres.setForeground(new java.awt.Color(255, 255, 255));
        btnListaAlquileres.setText("Listado de Alquileres");
        jPanel2.add(btnListaAlquileres);
        btnListaAlquileres.setBounds(30, 370, 190, 30);

        btnConfiguracion.setBackground(new java.awt.Color(51, 51, 255));
        btnConfiguracion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConfiguracion.setForeground(new java.awt.Color(255, 255, 255));
        btnConfiguracion.setText("Configuración");
        jPanel2.add(btnConfiguracion);
        btnConfiguracion.setBounds(30, 430, 170, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(250, 0, 250, 590);

        setSize(new java.awt.Dimension(500, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        
        // Mostrar el JOptionPane con las opciones Sí/No
        int respuesta = JOptionPane.showConfirmDialog(null, 
            "¿Deseas abrir otra ventana?", "Confirmación", 
            JOptionPane.YES_NO_OPTION);
        
        // Si el usuario selecciona "Sí" (YES_OPTION)
        if (respuesta == JOptionPane.YES_OPTION) {
            // Crear y mostrar otra ventana (puede ser un JOptionPane u otra ventana)
            JOptionPane.showMessageDialog(null, "¡Se abrió otra ventana!", 
                                          "Nueva Ventana", JOptionPane.INFORMATION_MESSAGE);
            frmLogin Regresar = new frmLogin();

            // Mostrar la nueva ventana
            Regresar.setVisible(true);

            // Cerrar la ventana actual
            this.dispose();
        } else {
            // Si el usuario selecciona "No" (NO_OPTION)
            /*JOptionPane.showMessageDialog(null, "No se abrirá otra ventana.", 
                                          "Cancelado", JOptionPane.INFORMATION_MESSAGE);*/
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAsignarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarVehiculoActionPerformed
        
    }//GEN-LAST:event_btnAsignarVehiculoActionPerformed

    private void btnRegistrarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVehiculoActionPerformed
       
        
    }//GEN-LAST:event_btnRegistrarVehiculoActionPerformed

    private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienteActionPerformed
        
        
    }//GEN-LAST:event_btnRegistrarClienteActionPerformed

    private void btnReporteIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteIngresosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteIngresosActionPerformed

    private void btnCalcularTarifasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularTarifasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularTarifasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarVehiculo;
    private javax.swing.JButton btnCalcularTarifas;
    private javax.swing.JButton btnConfiguracion;
    private javax.swing.JButton btnListaAlquileres;
    private javax.swing.JButton btnListaClientes;
    private javax.swing.JButton btnListaVehiculos;
    private javax.swing.JButton btnRegistrarCliente;
    private javax.swing.JButton btnRegistrarVehiculo;
    private javax.swing.JButton btnReporteIngresos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
