/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author USUARIO
 */
public class frmRegistrarClientes extends javax.swing.JFrame {

    /**
     * Creates new form frmRegistrarClientes
     */
    public frmRegistrarClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        btnClientes = new javax.swing.JButton();
        btnAgregarNuevoCliente = new javax.swing.JButton();
        btnGuardarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO DE CLIENTES");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(200, 30, 340, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 650, 90);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        jLabel2.setText("Codigo:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 60, 42, 16);

        jLabel3.setText("Nombres:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 90, 52, 16);

        jLabel4.setText("Telefono:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 130, 49, 16);

        jLabel5.setText("Direccion:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 170, 53, 16);

        jLabel6.setText("Email:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 220, 32, 16);

        jLabel7.setText("Ciudad:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 260, 41, 16);

        jLabel8.setText("Dni:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(300, 60, 40, 20);
        jPanel2.add(txtCodigo);
        txtCodigo.setBounds(80, 60, 200, 22);
        jPanel2.add(txtNombres);
        txtNombres.setBounds(90, 90, 390, 22);
        jPanel2.add(txtTelefono);
        txtTelefono.setBounds(90, 130, 160, 22);
        jPanel2.add(txtDireccion);
        txtDireccion.setBounds(90, 170, 390, 22);
        jPanel2.add(txtEmail);
        txtEmail.setBounds(90, 220, 390, 22);
        jPanel2.add(txtCiudad);
        txtCiudad.setBounds(81, 260, 400, 22);
        jPanel2.add(txtDni);
        txtDni.setBounds(340, 60, 160, 22);

        btnClientes.setBackground(new java.awt.Color(153, 255, 255));
        btnClientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Lupa.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setToolTipText("Clientes");
        jPanel2.add(btnClientes);
        btnClientes.setBounds(510, 80, 130, 120);

        btnAgregarNuevoCliente.setBackground(new java.awt.Color(102, 204, 255));
        btnAgregarNuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar.png"))); // NOI18N
        btnAgregarNuevoCliente.setToolTipText("Nuevo Cliente");
        jPanel2.add(btnAgregarNuevoCliente);
        btnAgregarNuevoCliente.setBounds(50, 0, 50, 40);

        btnGuardarCliente.setBackground(new java.awt.Color(102, 204, 255));
        btnGuardarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.png"))); // NOI18N
        btnGuardarCliente.setToolTipText("Guardar Cliente");
        jPanel2.add(btnGuardarCliente);
        btnGuardarCliente.setBounds(110, 0, 50, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 90, 650, 320);

        setSize(new java.awt.Dimension(666, 423));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistrarClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarNuevoCliente;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnGuardarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
